data:extend({
	-- Dummy Cooker
	{
		type = "item",
		name = "br-dummy-cooker",
		place_result = "br-dummy-cooker",
		stack_size = globals.CONSTANTS.BUILDING_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = globals.PLACEHOLDER.ITEM.SUBGROUP,
	},
	{
		type = "assembling-machine",
		name = "br-dummy-cooker",
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		flags = { "placeable-player", "player-creation", "placeable-neutral" },
		minable = { mining_time = 1, result = "br-dummy-cooker" },
		max_health = 200,
		collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
		selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
		animation = globals.PLACEHOLDER.ANIMATIONLAYERS,
		crafting_categories = { "br-cooking" },
		crafting_speed = 1,
		energy_source = {
			type = "void",
		},
		energy_usage = "1W",
	},
	-- Dummy Miller
	{
		type = "item",
		name = "br-dummy-miller",
		place_result = "br-dummy-miller",
		stack_size = globals.CONSTANTS.BUILDING_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = globals.PLACEHOLDER.ITEM.SUBGROUP,
	},
	{
		type = "assembling-machine",
		name = "br-dummy-miller",
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		flags = { "placeable-player", "player-creation", "placeable-neutral" },
		minable = { mining_time = 1, result = "br-dummy-miller" },
		max_health = 200,
		collision_box = { { -1.2, -1.2 }, { 1.2, 1.2 } },
		selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
		animation = globals.PLACEHOLDER.ANIMATIONLAYERS,
		crafting_categories = { "br-milling" },
		crafting_speed = 1,
		energy_source = {
			type = "void",
		},
		energy_usage = "1W",
	},
})
