data:extend({
	{
		type = "item",
		name = "br-oak-wood",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-tree",
		order = "b",
	},
	{
		type = "item",
		name = "br-brich-wood",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-tree",
		order = "b",
	},
	{
		type = "item",
		name = "br-mahogany-wood",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-tree",
		order = "b",
	},
	{
		type = "item",
		name = "br-palm-wood",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-tree",
		order = "b",
	},
})
