-- Crops
data:extend({
	{
		type = "item",
		name = "br-corn-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/corn-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-wheat-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/wheat-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-barley-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rye-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-cotton-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/cotton-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-hemp-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-flax-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/flax-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
})

-- Wild Seeds
data:extend({
	{
		type = "item",
		name = "br-corn-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/corn-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-wheat-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/wheat-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-barley-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rye-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-cotton-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/cotton-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-hemp-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-flax-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/flax-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
})
