-- Crops
data:extend({
	{
		type = "item",
		name = "br-corn-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/corn-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-wheat-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/wheat-crop.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-barley-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rye-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-cotton-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-hemp-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-flax-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
})

-- Wild Seeds
data:extend({
	{
		type = "item",
		name = "br-corn-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/corn-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-wheat-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.MODNAME .. "/graphics/icons/items/wheat-seed.png",
		icon_size = 64,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-barley-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rye-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-cotton-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-hemp-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-flax-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field-and-fibre",
	},
})
