-- Crops
data:extend({
	{
		type = "item",
		name = "br-corn-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-wheat-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-barley-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-rye-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-cotton-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-hemp-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-flax-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
})

-- Wild Seeds
data:extend({
	{
		type = "item",
		name = "br-corn-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-wheat-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-barley-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-rye-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-cotton-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-hemp-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-flax-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-sugarcane-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
	{
		type = "item",
		name = "br-rapeseed-wild_seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-field_and_fibre",
	},
})
