-- Crops
data:extend({
	{
		type = "item",
		name = "br-lettuce-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-peppers-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-brocolli-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-basil-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-rosemary-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-mint-crop",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
})

-- Wild Seeds
data:extend({
	{
		type = "item",
		name = "br-lettuce-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-peppers-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-brocolli-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-basil-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-rosemary-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-mint-wild-seed",
		stack_size = globals.CONSTANTS.CROP_STACK_SIZE,
		icon = globals.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = globals.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
})
