-- Crops
data:extend({
	{
		type = "item",
		name = "br-lettuce-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-peppers-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-brocolli-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-basil-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-rosemary-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-mint-crop",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
})

-- Wild Seeds
data:extend({
	{
		type = "item",
		name = "br-lettuce-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-peppers-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-brocolli-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-basil-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-rosemary-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
	{
		type = "item",
		name = "br-mint-seed",
		stack_size = biorev.STACKSIZE.CROP,
		icon = biorev.PLACEHOLDER.ITEM.ICON_FILEPATH,
		icon_size = biorev.PLACEHOLDER.ITEM.ICON_SIZE,
		subgroup = "br-agriculture-vegetable-and-herb",
	},
})
